### ISSUE TITLE
Runs every minute during 6pm

### ISSUE THREAD

**Issue by hidao80** [yoshi389111/yoshi389111#1]
With the current cron settings, I feel like it runs every minute during 6pm.

https://github.com/yoshi389111/yoshi389111/blob/85abec32c4faf659ce949c1f804f41e65f3ff2da/.github/workflows/profile-3d.yml#L5

How about this way?

```diff
- cron: "* 18 * * *"
+ cron: "0 18 * * *"
```

**Comment by yoshi389111** [comment]
thank you!
